const PostActionTypes = {
  GET_POSTS: "GET_POSTS",
  POST_ERROR: "POST_ERROR",
  UPDATE_LIKES: "UPDATE_LIKES",
  DELETE_POST: "DELETE_POST",
  ADD_POST: "ADD_POST",
  GET_POST: "GET_POST",
  CLEAR_STATE_POST: "CLEAR_STATE_POST",
  ADD_COMMENT: "ADD_COMMENT",
  REMOVE_COMMENT: "REMOVE_COMMENT",
};

export default PostActionTypes;
