export const ProfileActionTypes = {
  GET_PROFILE: "GET_PROFILE",
  GET_PROFILES: "GET_PROFILES",
  PROFILE_ERROR: "PROFILE_ERROR",
  CLEAR_PROFILE: "CLEAR_PROFILE",
  UPDATE_PROFILE: "UPDATE_PROFILE",
  ACCOUNT_DELETED: "ACCOUNT_DELETED",
  GET_REPOS: "GET_REPOS",
};
